config/routes.rb
LaunchDiary::Application.routes.draw do
  

  resources :categories
  resources :entries

end

app/models/category.rb
class Category < ActiveRecord::Base
	validates :name, presence: true
	validates :name, uniqueness: true
	has_many :entries
end

app/models/entry.rb
class Entry < ActiveRecord::Base
	validates :title, presence: true
	validates :description, presence: true

	belongs_to :category
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
	def index
		@categories = Category.all
	end

  def show
  	@category = Category.find(params[:id])
  end

  def new
  	@category = Category.new
  end

  def create
		@category = Category.new(category_params)
		if @category.save
      redirect_to '/categories', notice: "Category saved successfully."
    else
      render :new
    end
	end

  def edit
  	@category = Category.find(params[:id])
  end

  def update
  	@category = Category.find(params[:id])

    if @category.update_attributes(entry_params)
      redirect_to '/categories', notice: "Category saved successfully."
    else
      render :edit
    end
  end

  def destroy
    @category.destroy
    redirect_to '/categories', notice: "Category destroyed"
  end

  protected 
  def category_params
    params.require(:category).permit(:name)
  end
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
	def index
		@entries = Entry.all
	end
	def show
		@entry = Entry.find(params[:id])
	end
	def new
		@entry = Entry.new
	end
	def create
		@entry = Entry.new(entry_params)
		if @entry.save
      redirect_to '/entries', notice: "Entry saved successfully."
    else
      render :new
    end
	end
	def edit
    @entry = Entry.find(params[:id])
  end

  def update
    @entry = Entry.find(params[:id])

    if @entry.update_attributes(entry_params)
      redirect_to '/entries', notice: "Entry saved successfully."
    else
      render :edit
    end
  end

  protected 
  def entry_params
    params.require(:entry).permit(:title, :description, :category_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>

  <div>
    <%= f.label(:name) %>
    <%= f.text_field(:name) %>
  </div>

  <%= f.submit 'Save' %>

<% end %>

app/views/categories/edit.html.erb
<h1>Categories#edit</h1>
<p>Find me in app/views/categories/edit.html.erb</p>
<%= link_to(' Delete',category_path(category), method: delete) %>

app/views/categories/index.html.erb
<h1>categories</h1>
<p>
<% @categories.each do |category| %>
	<%= link_to(category.name,category_path(category)) %>
	<%= link_to(' Edit',edit_category_path(category)) %>
	<%= link_to 'Delete', category, method: :delete, data: { confirm: 'Are you sure?' } %>
	<br>
<% end %>

<br>

<%= link_to 'Add a Category', new_category_path %>

</p>

app/views/categories/new.html.erb
<h1>Create a new category</h1>
<%= render "categories/form", category: @category %>

app/views/categories/show.html.erb
<h1> <%= @category.name %> </h1>
<p>

<% @category.entries.each do |entry| %>
	<%= link_to(entry.title,entry_path(entry)) %>
	<br>
<% end %>
</p>

app/views/entries/_entry.html.erb
<h1><%= link_to(entry.title, entry_path(entry)) %></h1>
<p><%= entry.description %></p>
<br>

app/views/entries/_form.html.erb
<% if entry.errors.any? %>
  <ul>
    <% entry.errors.full_messages.each do |error| %>
      <li><%= error %></li> 
    <% end %>
  </ul>
<% end %>

<%= form_for(entry) do |f| %>
  <div>
    <%= f.label(:title) %>
    <%= f.text_field(:title) %>
  </div>

  <div>
    <%= f.label(:description) %>
    <%= f.text_area(:description) %>
  </div>

  <div>
    <%= f.label(:category_id) %>
    <%= f.collection_select(:category_id, Category.all, :id, :name) %>
  </div>


  <%= f.submit 'Save' %>
<% end %>

app/views/entries/index.html.erb
<h1>Entries</h1>
<p>
	<% @entries.each do |entry| %>
  	<%= render "entries/entry", entry: entry %>
	<% end %>

	<%= link_to 'Add an Entry', new_entry_path %>

</p>

app/views/entries/new.html.erb
<h1>Create an Entry</h1>

<%= link_to 'Back to Entries', entries_path %>

<%= render "entries/form", entry: @entry %>

app/views/entries/show.html.erb
<h1><%= @entry.title %> </h1>
<p><%= @entry.description %> </p>
<p>Category: <%= @entry.category.name unless @entry.category.blank? %></p>
<br>
<%= link_to('Entries',entries_path) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>LaunchDiary</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>